# Generated by Django 6.0.6 on 2026-07-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de documento'),
        ),
    ]
