# Generated by Django 6.0.7 on 2026-07-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
